EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(rtai_srcdir)/../.. \
		-I$(src)/../../../base/include \
		-I$(src)/../../.. \
		$(rtai_extradef)

obj-m += $(rtai_target).o

$(rtai_target)-objs := $(rtai_objs)
